### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by ankitjena** [zairza-cetb/zairza-website#24]
## Description
Currently there are a few unused dependencies in the server. And a few unnecessary code blocks for those.

## TODO
- [ ] Remove unused dependencies. This can be done using [`depcheck`](https://www.npmjs.com/package/depcheck) package. 
- [ ] Remove unnecessary code blocks in server side code, if any

**Comment by pragapraga** [comment]
I would like to work on this @ankitjena 😄

**Comment by ankitjena** [comment]
@pragapraga Go ahead
