### ISSUE TITLE
Replace gif with png/jpg

### ISSUE THREAD

**Issue by ankitjena** [zairza-cetb/zairza-website#28]
## Description
The image for IISc logo is in `gif` format. [here](https://1.bp.blogspot.com/-KxmBCARwbUw/Wdl7oaWZ6nI/AAAAAAAABvk/SMxsP91h6Dc5gj0039ONKuCX5SrZSsbwACLcBGAs/s1600/IISc_logo.gif)

## TODO
Replace it with a logo of IISc in `png` or `jpg` format.

**Comment by balvinderz** [comment]
Hello , i would like to do this but i can't find the iisc logo in your project.

**Comment by balvinderz** [comment]
This is the logo in png format ,if this what you want.
![IISc_logo](https://user-images.githubusercontent.com/30950893/66264664-740eb400-e827-11e9-8585-1fa9b8073bff.png)

**Comment by TotallyNotChase** [comment]
Hi, me again!
I'm supposed to add an src attribute before making the PR as you said, could you tell me the src attribute in which file please, thanks!

**Comment by ankitjena** [comment]
@TotallyNotChase it's in `achievements.ejs`
```
<div class="slide">
            <a href="#" data-toggle="tooltip" title="4 members selected for IISc summer fellowship">
                <img class="slide-image" src="https://1.bp.blogspot.com/-KxmBCARwbUw/Wdl7oaWZ6nI/AAAAAAAABvk/SMxsP91h6Dc5gj0039ONKuCX5SrZSsbwACLcBGAs/s1600/IISc_logo.gif" alt="indian institute of science">
            </a>
</div>
```

**Comment by TotallyNotChase** [comment]
Thanks! I added a direct link to the file in png format since I noticed you're using links for all the images.
Here's the [PR](https://github.com/zairza-cetb/zairza-website/pull/36).

**Comment by ankitjena** [comment]
@TotallyNotChase Nice
