### ISSUE TITLE
Add meta description

### ISSUE THREAD

**Issue by ankitjena** [zairza-cetb/zairza-website#30]
## Description
<meta> description tag should contain between 20 and 300 characters. This description is used in search engine results pages (SERP), such as Google results, to indicate a short informative text about the page.

## TODO
Add info about the website in description.

**Comment by stuntguy3000** [comment]
Do you propose the same description for each page or a generic one to be put on all pages?

**Comment by ankitjena** [comment]
@stuntguy3000 Just in the `index.ejs`. Keep the content same as the about us section. (a bit short, just the first few lines)
