### ISSUE TITLE
Remove node_modules

### ISSUE THREAD

**Issue by ankitjena** [zairza-cetb/zairza-website#42]
## Description
The repository contains `node_modules` folder which should be ignored always.

## TODO
Remove the `node_modules` folder and reconfigure `.gitgnore` with ideal `nodejs` gitignore file

**Comment by Akshay-911** [comment]
I can help with this.

**Comment by d-schaffer** [comment]
look my pull request. i removed the directory in my branch :)

**Comment by ankitjena** [comment]
@Akshay-911 already done.
