### ISSUE TITLE
Broken team page images

### ISSUE THREAD

**Issue by ankitjena** [zairza-cetb/zairza-website#48]
## Description
The imgur links added in `team.ejs` are broken, because the links are not correct.

## TODO
Modify the links so that the images are displayed. 
#### Current
```
https://imgur.com/pJMmCEA
```
#### Changed
```
https://i.imgur.com/pJMmCEA.jpg
```

**Comment by iam-abbas** [comment]
May I work on this?

**Comment by heytulsiprasad** [comment]
hello zairza! let me see if I can contribute for the issue, would be happy to help my college <3

**Comment by mehulagrawal** [comment]
Hi! I edited the links and added a pull request. I hope I didn't mess up.

**Comment by iam-abbas** [comment]
#50

**Comment by heytulsiprasad** [comment]
Hi, I have changed the links those were from facebook and others, by giving them direct links from imgur. But when I create a PR, it says review required. Looking fwd to reviews.
