### ISSUE TITLE
Correct the grammar of the website

### ISSUE THREAD

**Issue by ankitjena** [zairza-cetb/zairza-website#53]
## Description
There are a few grammatical errors in the website

## TODO
Correct the grammatical mistakes, you can use Grammarly for the purpose

**Comment by yordanzhelevdev** [comment]
I can do this

**Comment by thehashton** [comment]
Created a PR for it @ankitjena

**Comment by possum6** [comment]
I would like to fix up some grammar across all views - i am working on this now :)

**Comment by moby-dicc** [comment]
Sent a PR on it :D @ankitjena

**Comment by sahaj-singh** [comment]
I would like to work on this

**Comment by capturethemoon** [comment]
I can work on this.
