### ISSUE TITLE
Images are too large is size

### ISSUE THREAD

**Issue by ankitjena** [zairza-cetb/zairza-website#8]
## Description
The current images for team page and other images are too large in size. This increases the website load time. 

## TODO
Decrease the image size by losslessly compressing the images. There are many resources available. Example [https://compressor.io](https://compressor.io)

**Comment by ramyamahi** [comment]
I would like to do this

**Comment by ankitjena** [comment]
@ramyamahi Sure, go ahead.

**Comment by ankitjena** [comment]
@ramyamahi This was already done by someone. You can check out #10
