### ISSUE TITLE
Improve website SEO and performance

### ISSUE THREAD

**Issue by ankitjena** [zairza-cetb/zairza-website#9]
## Description
The current website has a huge load time. And many other issues.  It has a 61% rating on [dareboost.com](https://dareboost.com) which can be improved a lot.
![Screenshot_2019-10-05 Web Performance Report for https zairza in](https://user-images.githubusercontent.com/23580602/66254429-d4ecac80-e793-11e9-86ab-efd8f3b77a84.png)

## TODO
Go through the improvement suggesting in `dareboost`. Achieving this will take the performance rating above 75 - 80%.

>Note:  This issue can have multiple PRs

**Comment by ramyamahi** [comment]
#23

**Comment by ankitjena** [comment]
Closing this and dividing into multiple issues.
